name: Run Trading Simulation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      # تعديل بسيط لاسم الـ artifact ليكون أوضح
      - name: Upload simulation log
        uses: actions/upload-artifact@v4
        with:
          name: spread-only-simulation-log # اسم الـ artifact
          path: trading_simulation_log_spread_only.csv # مسار الملف الصحيح
